sudo: false

language: ruby

rvm:
  - 2.3.0

env:
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION='~> 4.0.0'"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION='~> 4.1.0'"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION='~> 4.2.0'"
  - "RAILS_VERSION=master"
